// src/lib/exporters/structguard.ts
import { BoardNode } from '@/types/board';

export function exportToStructGuardYAML(nodes: BoardNode[]): string {
    let yaml = 'version: "1.0"\nstructure:\n';

    function renderYamlNode(node: BoardNode, depth: number = 2) {
        const indent = ' '.repeat(depth);
        if (node.type === 'dir') {
            yaml += `${indent}- dir: ${node.name}\n`;
            if (node.children && node.children.length > 0) {
                yaml += `${indent}  contents:\n`;
                node.children.forEach(child => renderYamlNode(child, depth + 4));
            }
        } else {
            yaml += `${indent}- file: ${node.name}\n`;
            yaml += `${indent}  type: ${node.type}\n`;
        }
    }

    nodes.forEach(node => renderYamlNode(node, 2));
    return yaml;
}

// src/lib/exporters/shell-script.ts
export function exportToShellScript(nodes: BoardNode[]): string {
    let script = '#!/usr/bin/env bash\n# Generated by structboard\n\nset -e\n\n';

    function buildPaths(node: BoardNode, currentPath: string = ''): { dirs: string[], files: string[] } {
        const fullPath = currentPath ? `${currentPath}/${node.name}` : node.name;
        let dirs: string[] = [];
        let files: string[] = [];

        if (node.type === 'dir') {
            dirs.push(fullPath);
            if (node.children) {
                node.children.forEach(child => {
                    const res = buildPaths(child, fullPath);
                    dirs = dirs.concat(res.dirs);
                    files = files.concat(res.files);
                });
            }
        } else {
            files.push(fullPath);
        }

        return { dirs, files };
    }

    let allDirs: string[] = [];
    let allFiles: string[] = [];

    nodes.forEach(node => {
        const res = buildPaths(node);
        allDirs = allDirs.concat(res.dirs);
        allFiles = allFiles.concat(res.files);
    });

    if (allDirs.length > 0) {
        script += '# Create directories\n';
        allDirs.forEach(dir => {
            script += `mkdir -p "${dir}"\n`;
        });
        script += '\n';
    }

    if (allFiles.length > 0) {
        script += '# Create files\n';
        allFiles.forEach(file => {
            script += `touch "${file}"\n`;
        });
    }

    return script;
}